package com.tallerMecanico.domain.model.enums;

public enum ServiceType {
    CAMBIO_ACEITE,
    CAMBIO_FILTROS,
    AFINACION_MOTOR,

    CAMBIO_PASTILLAS_FRENO,
    RECTIFICACION_DISCOS,

    ALINEACION,
    BALANCEO,
    MONTAJE_LLANTA,
    REPARACION_LLANTA,
    CAMBIO_AMORTIGUADORES,

    DIAGNOSTICO_MOTOR,
    REPARACION_TRANSMISION,
    REPACION_EMBRAGUE,

    DIAGNOSTICO_ELECTICO,
    CAMBIO_BATERIA,

    RECARGA_AIRE_ACONDICIONADO,

    REPARACION_ESCAPE,

    PINTURA,
    ENDEREZADO,

    LAVADO,
    DETAILING
}
